### ISSUE TITLE
BCR presubmit: support specify a test module 

### ISSUE THREAD

**Issue by meteorcloudy** [bazelbuild/continuous-integration#1302]
Context: https://groups.google.com/a/bazel.build/g/external-deps/c/GcV1cpRd-Ls/m/1UU9Ez_DDQAJ

In the presubmit.yml file, allow BCR modules to specify a test module (with `bcr_test_module`, `module_path` and its task configurations) to verify the basic functionalities of the checked-in module. The top level of task configurations are only used to verify the build targets.

https://github.com/bazelbuild/continuous-integration/pull/1300 makes the configuration file simpler.

Example (https://github.com/meteorcloudy/bazel-central-registry/pull/7):
```
matrix:
  platform: ["centos7", "debian10", "macos", "ubuntu2004", "windows"]

tasks:
  verify_targets:
    name: "Verify build targets"
    platform: ${{ platform }}
    build_targets:
    - '@protobuf//:protobuf'
    - '@protobuf//:protobuf_lite'
    - '@protobuf//:protoc'
    - '@protobuf//:test_messages_proto2_proto_cc'

bcr_test_module:
  module_path: "examples"
  matrix:
    platform: ["centos7", "debian10", "macos", "ubuntu2004", "windows"]
  tasks:
    run_test_module:
      name: "Run test module"
      platform: ${{ platform }}
      build_targets:
      - "//..."
```
