### ISSUE TITLE
sudo brew install qt@5 takes forever

### ISSUE THREAD

**Issue by Vertexwahn** [bazelbuild/continuous-integration#1330]
I try to add macOS support for bazel_rules_qt [here](https://github.com/justbuchanan/bazel_rules_qt/pull/38).

To ensure this does not break in the future I added also a CI check for this to my PR.

In the CI job I try to install Qt5 using Homebrew. The job runs for more than 1 hour:
https://buildkite.com/bazel/rules-qt/builds/385#e814ad0e-436c-40ec-8c16-8680dc54db98

In a previous job run I canceled the job after 2 hours.
For some reason the command seems not to work or is very, very slow. Any hints form me how to make this faster?

**Comment by fweikert** [comment]
FYI, I cancelled two presubmit runs since Mac resources are in demand right now. They've been running for over two and five hours, respectively.

**Comment by Vertexwahn** [comment]
This is what the .`bazelci/presubmit.yml` looks like:

```
---
tasks:
  ubuntu2004:
    platform: ubuntu2004
    shell_commands:
      - "sudo apt update && sudo apt -y install qt5-default qtdeclarative5-dev"
    build_targets:
      - "//..."
  macos:
    shell_commands:
      - "sudo brew install qt@5"
    build_targets:
      - "//..."
```

I just want to install Qt (`sudo brew install qt@5`) dependencies - this takes ages - no idea why...
