### ISSUE TITLE
Using import "foo.yml" syntax expects the working directory to be "foo"

### ISSUE THREAD

**Issue by aiuto** [bazelbuild/continuous-integration#1361]
This is a strange and undocumented feature.  It means you can't easily split sections of the yaml up by logical grouping. Instead, it expects sections to be by file system layout.  For example, if you called the include file `tutorials.yml`, but actual things were scattered, we have to   work around it with things like
```
tutorials.yml

tasks:
  concept1:
     working_directory: ../training/concept1
  getting_started:
     working_directory: ../basics/getting_started
```
