### ISSUE TITLE
Maybe support for a build after tests

### ISSUE THREAD

**Issue by thomasvl** [bazelbuild/continuous-integration#232]
For rules repos, they tend to include some examples.  Building (and testing) on the examples is useful to make sure they always work, but it would be nice to do that `build` & `test` after the "main" `build`/`test` on the repo as that main pair is going to include specific tests for all the rules/features of the repo.  So if something breaks in the examples, it will be less obvious exactly what went wrong compared to see the test results.

Right now, the examples end up mixed in, so if an example fails, you likely don't get as easy of output to pinpoint the issue on as seeing the tests fail would.

**Comment by buchgr** [comment]
You should be able to do `bazel test //actual:test //build:target` and that will build both targets but only run the test and report any build failures. We have `--keep_going` enabled on our CI by default.

**Comment by thomasvl** [comment]
That appears to mostly work.  I say mostly because it looks like bazel is still free to run jobs in the order it decides, so our example builds/tests seem to mix with the actual testing of the rules.  So you can still end up having to scroll through them to find the more specific failures.

**Comment by philwo** [comment]
The current supported way for this is to add multiple tasks in the pipeline config:

```yaml
---
tasks:
  ubuntu1804:
    platform: ubuntu1804
    build_targets:
    - "//stuff"
    test_targets:
    - "//tests"
  ubuntu1804_examples:
    name: "Examples"
    platform: ubuntu1804
    build_targets:
    - "//examples"
```

See: https://github.com/bazelbuild/continuous-integration/blob/master/buildkite/README.md#basic-syntax

Would that work?
