### ISSUE TITLE
Mac does not have python2 in path

### ISSUE THREAD

**Issue by nlopezgi** [bazelbuild/continuous-integration#854]
I'm getting the following error on BuildKite macos:
```
Execution platform: @local_config_platform//:host
 
Use --sandbox_debug to see verbose messages from the sandbox
env: python2: No such file or directory
```
I checked with the shell_commands and it does seem there is no such file in the path. Seems it should be there if python autodetected toolchains needs it?
Context: https://github.com/bazelbuild/rules_k8s/pull/453

**Comment by nlopezgi** [comment]
Managed to get around this problem by manually creating the python2 symlink in /tmp/bin and hardcoding a path, nasty but works as a temporary runaround:
```
 macos:
    shell_commands:
    - mkdir /tmp/bin
    - ln -s /usr/bin/python2.7 /tmp/bin/python2
    build_targets:
    - "--"
    build_flags:
    - "--verbose_failures"
    - "--action_env=PATH=/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/tmp/bin/"
```
